/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_syslog_ng_LogParser */

#ifndef _Included_org_syslog_ng_LogParser
#define _Included_org_syslog_ng_LogParser
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
